services:
  app:
    build: .
    container_name: horizoncp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../web:/var/www
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - horizoncp_network

  webserver:
    image: nginx:latest
    container_name: horizoncp_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../web:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - horizoncp_network

  db:
    image: mariadb:latest
    container_name: horizoncp_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: horizoncp
      MYSQL_USER: horizoncp_user
      MYSQL_PASSWORD: horizoncp_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - horizoncp_network

  redis:
    image: redis:alpine
    container_name: horizoncp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - horizoncp_network

volumes:
  db_data:

networks:
  horizoncp_network:
    driver: bridge
